openapi: 3.0.0
info:
  title: Todo Tasks API
  description: API for managing user tasks in the Todo application
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
    description: Development server

paths:
  /tasks:
    get:
      summary: Get user's tasks
      description: Retrieve a list of tasks for the authenticated user
      security:
        - BearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
          description: Page number for pagination
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
          description: Number of tasks per page
        - name: completed
          in: query
          schema:
            type: boolean
          description: Filter tasks by completion status
      responses:
        '200':
          description: List of user's tasks
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
                  total:
                    type: integer
                  page:
                    type: integer
                  limit:
                    type: integer
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '500':
          description: Internal server error

    post:
      summary: Create a new task
      description: Create a new task for the authenticated user
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid request data
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '500':
          description: Internal server error

  /tasks/{id}:
    get:
      summary: Get a specific task
      description: Retrieve a specific task by ID for the authenticated user
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Task ID
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '404':
          description: Task not found
        '500':
          description: Internal server error

    put:
      summary: Update a task
      description: Update an existing task for the authenticated user
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Task ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid request data
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '404':
          description: Task not found
        '500':
          description: Internal server error

    delete:
      summary: Delete a task
      description: Delete a task for the authenticated user
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Task ID
      responses:
        '204':
          description: Task deleted successfully
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '404':
          description: Task not found
        '500':
          description: Internal server error

    patch:
      summary: Toggle task completion
      description: Toggle the completion status of a task
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Task ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                completed:
                  type: boolean
              required:
                - completed
      responses:
        '200':
          description: Task completion status updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid request data
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '404':
          description: Task not found
        '500':
          description: Internal server error

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          description: Unique task identifier
        title:
          type: string
          description: Task title
          minLength: 1
          maxLength: 255
        description:
          type: string
          description: Task description (optional)
          maxLength: 1000
        completed:
          type: boolean
          description: Completion status
          default: false
        createdAt:
          type: string
          format: date-time
          description: Task creation timestamp
        updatedAt:
          type: string
          format: date-time
          description: Task last update timestamp
        userId:
          type: string
          description: Owner user ID
      required:
        - id
        - title
        - completed
        - createdAt
        - updatedAt
        - userId

    TaskCreate:
      type: object
      properties:
        title:
          type: string
          description: Task title
          minLength: 1
          maxLength: 255
        description:
          type: string
          description: Task description (optional)
          maxLength: 1000
        completed:
          type: boolean
          description: Initial completion status
          default: false
      required:
        - title

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          description: Task title
          minLength: 1
          maxLength: 255
        description:
          type: string
          description: Task description (optional)
          maxLength: 1000
        completed:
          type: boolean
          description: Completion status
      required:
        - title